[
  {
    "instruction": "CATIA中使用VBS实现一个获取CATIA应用程序对象的函数。",
    "input": "",
    "output": "下面是一个使用微软VBA语言编写的获取CATIA应用程序实例的函数，该函数没有参数，返回获取的CATIA应用程序实例。\\n\\n```VBA\\nFunction GetCATIAApplication()\\n    Dim catiaApp As Object\\n\\n    Try\\n        '使用GetObject函数获取COM组件的实例\\n        catiaApp = GetObject(\"\", \"CATIA.Application\")\\n        '(INFITF.Application)Marshal.GetActiveObject(\"CATIA.Application\")\\n\\n    Catch ex1 As Exception\\n        '捕获并处理异常\\n        'WScript.Echo(\"can not get catia, create instance:{0}\", ex1.Message)\\n        'Console.WriteLine(\"can not get catia, create instance:{0}\", ex1.Message)\\n        'ConcatMessagesStrings(False, \"can not get catia, create instance:\", ex1.Message)\\n        Debug.Print \"can not get catia, create instance:\" & ex1.Message\\n\\n        Try\\n            '创建Catia应用程序实例\\n            catiaApp = CreateObject(\"CATIA.Application\")\\n        Catch ex2 As Exception\\n            'ConcatMessagesStrings(False, \"create instance error:\", ex1.Message)\\n            Debug.Print \"create instance error:\" & ex1.Message\\n            Exit Sub\\n        End Try\\n\\n    End Try\\n\\n    If catiaApp Is Nothing Then\\n        'ConcatMessagesStrings(True, \"Can not get CATIA appliction!\")\\n        Debug.Print \"Can not get CATIA appliction!\"\\n        Exit Sub\\n    End If\\n\\n    '设置为true可使Catia界面可见\\n    catiaApp.Visible = True\\n\\n    GetCATIAApplication catiaApp\\nEnd Function\\n```\\n\\n这个函数首先使用GetObject方法获取CATIA应用程序实例。如果返回空，就使用CreateObject方法来创建一个实例，并返回。\\n\\n例如，可以这样调用该函数来获取CATIA应用程序实例:\\n```vba\\nDim CATIA As CATIA.Application\\nSet CATIA = GetCATIAApplication\\n\\nIf Not CATIA Is Nothing Then\\n    MsgBox \"成功获取了CATIA应用程序对象。\", vbInformation\\nElse\\n    MsgBox \"无法获取CATIA应用程序对象。请检查代码。\", vbExclamation\\nEnd If\\n```"
  },
{
    "instruction": "写一个CATIA的VBS函数来获取获取CATIA应用程序对象。",
    "input": "",
    "output": "下面是一个使用微软VBA语言编写的获取CATIA应用程序实例的函数，该函数没有参数，返回获取的CATIA应用程序实例。\\n\\n```VBA\\nFunction GetCATIAApplication()\\n    Dim catiaApp As Object\\n\\n    Try\\n        '使用GetObject函数获取COM组件的实例\\n        catiaApp = GetObject(\"\", \"CATIA.Application\")\\n        '(INFITF.Application)Marshal.GetActiveObject(\"CATIA.Application\")\\n\\n    Catch ex1 As Exception\\n        '捕获并处理异常\\n        'WScript.Echo(\"can not get catia, create instance:{0}\", ex1.Message)\\n        'Console.WriteLine(\"can not get catia, create instance:{0}\", ex1.Message)\\n        'ConcatMessagesStrings(False, \"can not get catia, create instance:\", ex1.Message)\\n        Debug.Print \"can not get catia, create instance:\" & ex1.Message\\n\\n        Try\\n            '创建Catia应用程序实例\\n            catiaApp = CreateObject(\"CATIA.Application\")\\n        Catch ex2 As Exception\\n            'ConcatMessagesStrings(False, \"create instance error:\", ex1.Message)\\n            Debug.Print \"create instance error:\" & ex1.Message\\n            Exit Sub\\n        End Try\\n\\n    End Try\\n\\n    If catiaApp Is Nothing Then\\n        'ConcatMessagesStrings(True, \"Can not get CATIA appliction!\")\\n        Debug.Print \"Can not get CATIA appliction!\"\\n        Exit Sub\\n    End If\\n\\n    '设置为true可使Catia界面可见\\n    catiaApp.Visible = True\\n\\n    GetCATIAApplication catiaApp\\nEnd Function\\n```\\n\\n这个函数首先使用GetObject方法获取CATIA应用程序实例。如果返回空，就使用CreateObject方法来创建一个实例，并返回。\\n\\n例如，可以这样调用该函数来获取CATIA应用程序实例:\\n```vba\\nDim CATIA As CATIA.Application\\nSet CATIA = GetCATIAApplication\\n\\nIf Not CATIA Is Nothing Then\\n    MsgBox \"成功获取了CATIA应用程序对象。\", vbInformation\\nElse\\n    MsgBox \"无法获取CATIA应用程序对象。请检查代码。\", vbExclamation\\nEnd If\\n```"
  },
  {
    "instruction": "使用CATIA的VBS语言，实现一个函数，用来获取获取CATIA应用程序对象。",
    "input": "",
    "output": "下面是一个使用微软VBA语言编写的获取CATIA应用程序实例的函数，该函数没有参数，返回获取的CATIA应用程序实例。\\n\\n```VBA\\nFunction GetCATIAApplication()\\n    Dim catiaApp As Object\\n\\n    Try\\n        '使用GetObject函数获取COM组件的实例\\n        catiaApp = GetObject(\"\", \"CATIA.Application\")\\n        '(INFITF.Application)Marshal.GetActiveObject(\"CATIA.Application\")\\n\\n    Catch ex1 As Exception\\n        '捕获并处理异常\\n        'WScript.Echo(\"can not get catia, create instance:{0}\", ex1.Message)\\n        'Console.WriteLine(\"can not get catia, create instance:{0}\", ex1.Message)\\n        'ConcatMessagesStrings(False, \"can not get catia, create instance:\", ex1.Message)\\n        Debug.Print \"can not get catia, create instance:\" & ex1.Message\\n\\n        Try\\n            '创建Catia应用程序实例\\n            catiaApp = CreateObject(\"CATIA.Application\")\\n        Catch ex2 As Exception\\n            'ConcatMessagesStrings(False, \"create instance error:\", ex1.Message)\\n            Debug.Print \"create instance error:\" & ex1.Message\\n            Exit Sub\\n        End Try\\n\\n    End Try\\n\\n    If catiaApp Is Nothing Then\\n        'ConcatMessagesStrings(True, \"Can not get CATIA appliction!\")\\n        Debug.Print \"Can not get CATIA appliction!\"\\n        Exit Sub\\n    End If\\n\\n    '设置为true可使Catia界面可见\\n    catiaApp.Visible = True\\n\\n    GetCATIAApplication catiaApp\\nEnd Function\\n```\\n\\n这个函数首先使用GetObject方法获取CATIA应用程序实例。如果返回空，就使用CreateObject方法来创建一个实例，并返回。\\n\\n例如，可以这样调用该函数来获取CATIA应用程序实例:\\n```vba\\nDim CATIA As CATIA.Application\\nSet CATIA = GetCATIAApplication\\n\\nIf Not CATIA Is Nothing Then\\n    MsgBox \"成功获取了CATIA应用程序对象。\", vbInformation\\nElse\\n    MsgBox \"无法获取CATIA应用程序对象。请检查代码。\", vbExclamation\\nEnd If\\n```"
  }
]
